name: Build Swift DocC and publish to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_TARGET: SetlistFMKit

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Swift environment
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.8'
        
    - name: Fetch all branches
      run: git fetch --all

    - name: Build docs with SwiftPM
      run: |
        swift package --allow-writing-to-directory ./docs \
        generate-documentation --target ${BUILD_TARGET} \
        --output-path ./docs \
        --disable-indexing \
        --transform-for-static-hosting \
        --hosting-base-path ${BUILD_TARGET}
        
    - name: Clean untracked files
      run: git clean -fd

    - name: Commit and push generated documentation
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Stash changes so that you can apply them on top of gh-pages branch
        git stash

        # Switch to gh-pages branch and apply the documentation changes
        git switch gh-pages
        git pull origin gh-pages
        git stash apply

        # Add the changes
        git add ./docs

        # Try to commit. If no changes, this will fail, so don't stop the workflow.
        git commit -a -m "Generated Swift DocC" || echo "No changes to commit"

        git push origin gh-pages
